/**
 * Extracts the framework-agnostic CSS from glass-ui-solid (a SolidJS library we only
 * use for its look) into src/styles/glass-ui.css.
 *
 * The package ships a full Tailwind build. We keep:
 *   - @layer theme / properties (design tokens, @property registrations)
 *   - every unlayered rule (.glass-* component classes) wrapped in @layer components
 * and drop its preflight (@layer base) and utilities so they cannot override ours.
 *
 * Run: bun scripts/sync-glass-css.ts   (also runs on postinstall)
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const src = resolve(root, "node_modules/glass-ui-solid/dist/styles.css");
const out = resolve(root, "src/styles/glass-ui.css");
const css = readFileSync(src, "utf8");

/** Split CSS into top-level statements (rules or at-rules), respecting nesting and strings. */
function topLevel(text: string): string[] {
  const parts: string[] = [];
  let depth = 0,
    start = 0,
    quote: string | null = null;
  for (let i = 0; i < text.length; i++) {
    const c = text[i]!;
    if (quote) {
      if (c === "\\") {
        i++;
      } else if (c === quote) {
        quote = null;
      }
      continue;
    }
    if (c === '"' || c === "'") {
      quote = c;
      continue;
    }
    if (c === "/" && text[i + 1] === "*") {
      i = text.indexOf("*/", i + 2) + 1;
      continue;
    }
    if (c === "{") {
      depth++;
    } else if (c === "}") {
      depth--;
      if (depth === 0) {
        parts.push(text.slice(start, i + 1).trim());
        start = i + 1;
      }
    } else if (c === ";" && depth === 0) {
      parts.push(text.slice(start, i + 1).trim());
      start = i + 1;
    }
  }
  return parts.filter(Boolean);
}

const keptLayers: string[] = [];
const components: string[] = [];
for (const stmt of topLevel(css)) {
  const m = /^@layer\s+([\w-]+)\s*[{;]/.exec(stmt);
  if (m) {
    const name = m[1];
    if (stmt.endsWith(";")) {
      continue; // bare layer declaration
    }
    if (name === "theme" || name === "properties") {
      keptLayers.push(stmt);
    }
    continue; // base + utilities dropped
  }
  if (stmt.startsWith("@import") || stmt.startsWith("@charset")) {
    continue;
  }
  components.push(stmt);
}

const banner = `/* GENERATED by scripts/sync-glass-css.ts from glass-ui-solid — do not edit. */\n`;
const body = `${banner}${keptLayers.join("\n")}\n@layer components {\n${components.join("\n")}\n}\n`;
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, body);
console.log(
  `glass-ui.css: ${keptLayers.length} token layers, ${components.length} component rules, ${(body.length / 1024).toFixed(1)} kB`,
);
